### ISSUE TITLE
Check 'request_order' PHP variable for Joomla 4  sites

### ISSUE THREAD

**Issue by Sulpher** [akeeba/kickstart#28]
An interesting issue with #Joomla4 multilingual sites was investigated.

https://github.com/joomla/joomla-cms/issues/35541

Just a suggestion to add checking the 'request_order' PHP variable in Kickstart and recommend a user to set the right value (amongst other server recommendations like register globals off and etc)

**Comment by nikosdion** [comment]
Kickstart only extract archives. It does not know what they contain. I suppose you meant that ANGIE should check that.

I am not going to implement that unless it becomes an official requirement or recommendation of Joomla. In my opinion, it shouldn't be a requirement or recommendation. Joomla should be able to operate regardless of the variable registration order. It actually does, you just bumped into a very edge case.

FWIW the correct solution is to change this line in Joomla's input class:
```php
$this->data    = empty($source) ? $_REQUEST : $source;
```
to
```
$this->data    = is_null($source) ? $_REQUEST : $source;
```
In my opinion this should be reported to the Joomla Security Strike Team (JSST) because it's a hidden security issue.

And, really, your issue is definitely NOT the variable registration order. This was the trigger for a visible artifact. The real issue is the way Joomla's Input works.

**Comment by nikosdion** [comment]
Also for your information, when we forked Joomla's Input class for use in our WordPress software we had discovered this issue and addressed it (that was back in December 2014): https://github.com/akeeba/awf/blob/e6eb5f1f9e5d66a72bc151dee560a602854d298f/src/Input/Input.php#L77-L111

Apparently I had bumped into a similar problem thanks to WordPress being infinitely more wonky than Joomla 🤷🏽‍♂️

In any case, I am going to mark this as invalid because it's really a bug in Joomla, not something we should do anything about on our end.

**Comment by Sulpher** [comment]
Yes, I meant Angie. 
Thank you for your prompt response, Nick! You're right - it is better to see an official statement first.

**Comment by nikosdion** [comment]
I pinged the right people on your Joomla issue. It's actually quite a major security issue. Request variable shading is very frequently used by attackers. I can't think of a practical way to exploit it in core Joomla 4 but given that the Input object underpins the operation of every single core and third party Joomla extension the [theorem of infinite monkeys](https://en.wikipedia.org/wiki/Infinite_monkey_theorem) says that this will cause at least one major security issue in an unsuspecting, well–written extension.
