### ISSUE TITLE
the latest release 5.5.0 don't work

### ISSUE THREAD

**Issue by wdammak** [akeeba/kickstart#7]
I saw the archive 5.5.0 directly from the site akeebabackup, the script doesn't work from the beginning indeed it shows me this error message
Note: Using the undefined constant KSSELFNAME - assumed "KSSELFNAME" in C:\wamp\www\extract\kickstart.php on line 7291
and when launching the extraction, he shows me the following error message:
AJAX loading error
HTTP status: 0 (error)
Internal status: error
XHR ReadyState: 0
Raw server response:

I solved this problem by adding the definition of KSSELFNAME at the beginning of the script (Line 87):
```
if (!defined('KSSELFNAME'))
{
	define('KSSELFNAME', basename(__FILE__, '.php'));
}
```

Fixed

**Comment by wdammak** [comment]
after a quick consultation of the code the error comes from the importKickstartFeatures function
you may need to run the script in a blank folder to simulate the error.

**Comment by nikosdion** [comment]
This is not an error, just a warning, which has no bearing to the operation of Kickstart. It happens when it's looking for language files. I have fixed it now BUT it has nothing to do with the error you are getting.

The problem is that WAMP is using a PHP non-thread-safe build as an Apache module. This causes PHP to randomly crash. I recommend using MAMP instead.
